### ISSUE TITLE
chef-client v12 breaks chef-rewind

### ISSUE THREAD

**Issue by scalp42** [bryanwb/chef-rewind#21]
Unwinding a resource cause Chef run to fail:

```
unwind 'template[/etc/logrotate.d/chef-client]'
```

Error is:

```
 NoMethodError
  -------------
  undefined method `delete_if' for nil:NilClass
```

Worked fine until the upgrade of today:

```
root@mongodb-i-d03994fa [dev14] ~ # chef-client -v
Chef: 12.0.0
```

Looking into it, just opening for visibility.

**Comment by scalp42** [comment]
Any updates @thommay ?

**Comment by thommay** [comment]
Yeah, fixed in the latest release last month.

**Comment by scalp42** [comment]
I guess we're just confused because what's in Rubygems is not matching the repo (at least master) @thommay

**Comment by thommay** [comment]
The homepage link in the rubygem points to thommay/chef-rewind@master now. I'll push something to this repo to make that clear
